receitasnet/config/routes.rb
Rails.application.routes.draw do

  root 'recipes#index'
  resources :recipes
end

receitasnet/app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

receitasnet/app/models/recipe.rb
class Recipe < ApplicationRecord

    def light?
        calories < 100
    end

    def self.created_at
        where('created_at <= ?', Time.now).order('created_at desc')
    end
end

receitasnet/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

receitasnet/app/controllers/recipes_controller.rb
class RecipesController < ApplicationController

    def index
        @recipes = Recipe.created_at
    end

    def show
        @recipe = Recipe.find(params[:id])
    end

    def edit
        @recipe = Recipe.find(params[:id])
    end

    def update
        @recipe = Recipe.find(params[:id])
        @recipe.update(recipe_params)
        redirect_to @recipe
    end

    def new
        @recipe = Recipe.new
    end

    def create
        @recipe = Recipe.new(recipe_params)
        @recipe.save
        redirect_to @recipe
    end

    def destroy
        @recipe = Recipe.find(params[:id])
        @recipe.destroy
        redirect_to recipes_url
    end

    private

        def recipe_params
            params.require(:recipe).permit(:name, :stuff, :calories, :prepare_mode, :cost, :kind, :portion, :duration, :poster)
        end
end

receitasnet/app/helpers/application_helper.rb
module ApplicationHelper
end

receitasnet/app/helpers/recipes_helper.rb
module RecipesHelper

    def formata_caloria(recipe)
        if recipe.light?
            content_tag(:strong, "Light(Menos de 100 calorias)")
        else
            recipe.calories
        end
    end

    def imagem(recipe)
        if recipe.poster.blank?
            image_tag('sem-imagem.gif')
        else
            image_tag(recipe.poster)
        end
    end
end

receitasnet/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Receitasnet</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

receitasnet/app/views/recipes/_form.html.erb
<%= form_for(@recipe) do |f| %>

<p>
<%= f.label :Nome %></br>
<%= f.text_field :name %>
</p>
<p>
<%= f.label :Ingredientes %></br>
<%= f.text_area :stuff, cols:20, rows:5 %>
</p>
<p>
<%= f.label :Tipo %></br>
<%= f.text_field :kind %>
</p>
<p>
<%= f.label :Calorias %></br>
<%= f.number_field :calories %>
</p>
<p>
<%= f.label :Modo_de_preparo %></br>
<%= f.text_area :prepare_mode, cols:20, rows:5 %>
</p>
<p>
<%= f.label :Tempo_de_preparo %></br>
<%= f.time_select :duration %>
</p>
<p>
<%= f.label :Porções %></br>
<%= f.text_field :portion %>
</p>
<p>
<%= f.label :Custo %></br>
<%= f.number_field :cost %>
</p>
<p>
<%= f.label :Poster %></br>
<%= f.text_field :poster, placeholder: ".GIF, .JPEG, ou .PNG" %>
</p>
<p>
    <%= f.submit %>
    <%= link_to 'Cancelar', root_path %>
</p>

<% end %>

receitasnet/app/views/recipes/edit.html.erb
<h1>Editando Receitas</h1>

<%= render 'form' %>

receitasnet/app/views/recipes/index.html.erb
<h1><%= pluralize(@recipes.size, "Receita", "Receitas") %></h1>

<% @recipes.each do |recipe| %>
    <article>
        <header>
            <h2><%= link_to recipe.name , recipe %></h2>
            <%= imagem(recipe) %>
        </header>
        <p>
            <%= truncate(recipe.stuff, length:15, separator: '') %>
        </p>
        <p>
            <%= formata_caloria(recipe) %>
        </p>
        <p>
            <%= recipe.duration.to_formatted_s(:time) %> min
        </p>


        <table>
            <tr>
                <th>Modo de Preparo:</th>
                <td><%= recipe.prepare_mode %></td>
            </tr>
            <th>Custo do Preparo:</th>
                <td><%= number_to_currency(recipe.cost) %></td>
            </tr>
        </table>
    </article>
<% end %>
</br>

<%= link_to 'Nova Receita', new_recipe_path %>

receitasnet/app/views/recipes/new.html.erb
<h1>Criando Receita</h1>

<%= render 'form' %>

receitasnet/app/views/recipes/show.html.erb
<article>
    <header>
        <h1><%= @recipe.name %></h1>
        <%= imagem(@recipe) %>
    </header>
    <h2>Tipo</h2>
    <p>
        <%= @recipe.kind %>
    </p>
    <h2>Ingredientes</h2>
    <p>
        <%= @recipe.stuff %>
    </p>
    <h2>Calorias</h2>
    <p>
        <%= @recipe.calories %>
    </p>
    <h3>Modo de Preparo</h3>
    <p>
        <%= @recipe.prepare_mode %>
    </p>
    <h3>Tempo de Preparo</h3>
    <p>
        <%= @recipe.duration.to_formatted_s(:time) %> min
    </p>
    <h3>Porções</h3>
    <p>
        <%= pluralize(@recipe.portion, 'porção', 'porções') %>
    </p>
    <h3>Custo</h3>
    <p>
        <%= @recipe.cost %>
    </p>
</article>

<%= link_to "Receitas", recipes_path %>
<%= link_to "Editar receita", edit_recipe_path(@recipe) %>
<%= link_to "Deletar receita", recipe_path(@recipe), method: :delete, data:{ confirm: "Deseja deletar esta Receita?"} %>